//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Blog.DAL
{
    using System;
    using System.Collections.Generic;
    using System.Web.Mvc;

    public partial class Konu
    {
        public int ID { get; set; }
        public string Baslik { get; set; }

        [AllowHtml]
        public string Icerik { get; set; }
        public System.DateTime Tarih { get; set; }
        public int OneCikar { get; set; }
        public int UyeID { get; set; }
        public int KategoriID { get; set; }
        public string Resim { get; set; }
    
        public virtual Kategori Kategori { get; set; }
        public virtual Uye Uye { get; set; }
    }
}
